[package]
name = "vuk"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.59.2"

[build-dependencies]
bindgen = "0.59.2"
